//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpChanger {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UserDefinedSaves : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserDefinedSaves defaultInstance = ((UserDefinedSaves)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserDefinedSaves())));
        
        public static UserDefinedSaves Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig1ip {
            get {
                return ((string)(this["konfig1ip"]));
            }
            set {
                this["konfig1ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig1subnet {
            get {
                return ((string)(this["konfig1subnet"]));
            }
            set {
                this["konfig1subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig1gateway {
            get {
                return ((string)(this["konfig1gateway"]));
            }
            set {
                this["konfig1gateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig2ip {
            get {
                return ((string)(this["konfig2ip"]));
            }
            set {
                this["konfig2ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig2subnet {
            get {
                return ((string)(this["konfig2subnet"]));
            }
            set {
                this["konfig2subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig2gateway {
            get {
                return ((string)(this["konfig2gateway"]));
            }
            set {
                this["konfig2gateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig3ip {
            get {
                return ((string)(this["konfig3ip"]));
            }
            set {
                this["konfig3ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig3subnet {
            get {
                return ((string)(this["konfig3subnet"]));
            }
            set {
                this["konfig3subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig3gateway {
            get {
                return ((string)(this["konfig3gateway"]));
            }
            set {
                this["konfig3gateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig4ip {
            get {
                return ((string)(this["konfig4ip"]));
            }
            set {
                this["konfig4ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig4subnet {
            get {
                return ((string)(this["konfig4subnet"]));
            }
            set {
                this["konfig4subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig4gateway {
            get {
                return ((string)(this["konfig4gateway"]));
            }
            set {
                this["konfig4gateway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig5ip {
            get {
                return ((string)(this["konfig5ip"]));
            }
            set {
                this["konfig5ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig5subnet {
            get {
                return ((string)(this["konfig5subnet"]));
            }
            set {
                this["konfig5subnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string konfig5gateway {
            get {
                return ((string)(this["konfig5gateway"]));
            }
            set {
                this["konfig5gateway"] = value;
            }
        }
    }
}
